### PR TITLE
Fix package bug

### LINKED ISSUE #7: Installation fails
`:CocInstall coc-cl` gives me `coc-cl main file lib/index.js not found, you may need to build the project.`, both on Windows and on FreeBSD.

### PR DESCRIPTION
**Pull request by Freed-Wu**
Now npm publish will publish correct package to npm.

Fix #7

### CODE REVIEW

**Comment by UltiRequiem** [comment]
will publish later today

**Comment by avysk** [comment]
You didn't publish, did you?

**Comment by UltiRequiem** [comment]
> You didn't publish, did you?

https://www.npmjs.com/package/coc-cl?activeTab=versions

you can check here

**Comment by avysk** [comment]
It shows coc-zig as a repository for a package, by the way.

Excuse me for asking, but are you going to publish soon?

**Comment by UltiRequiem** [comment]
I may

**Comment by UltiRequiem** [comment]
> It shows coc-zig as a repository for a package, by the way.

fixed

**Pull request merged**
